[tool.poetry]
name = "MrLixm.github.io"
version = "1.0.0"
description = "Personal website and blog repository."
authors = ["Liam Collod <lcollod@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "8.4.0"
ghp-import = "2.0.2"
pelican = "4.7.2"
Pygments = "2.10.0"
docutils-stubs = "0.0.22"

[tool.poetry.dev-dependencies]
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
