# Project information
site_name: MrLixm Website
site_author: Collod Liam
site_description: >-
  Personal blog & website for Liam Collod (MrLixm)

# Copyright
copyright: Copyright &copy; 2020 - 2020 Collod-Liam

nav:
    - Home: index.md

theme:
  name: material
  features: -tabs
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    scheme: slate
#    primary: indigo
#    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo_lixm.png
  favicon: img/logo_lixm.png

markdown_extensions:
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MrLixm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/liam-collod/
    - icon: fontawesome/brands/artstation
      link: https://www.artstation.com/monsieur_lixm


